ieq_cifras/BluePrints/band/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

from ieq_cifras.models import User

class NewBandForm(FlaskForm):
    name = StringField(
        'Band Name',
        validators=[
            DataRequired(),
            Length(min=2, max=30)
        ]
    )

    submit = SubmitField('Create Band')

ieq_cifras/BluePrints/band/__init__.py
from flask import Blueprint, Flask

bp_band = Blueprint('band', __name__, url_prefix='/band', template_folder='templates')
from . import routes

def init_app(app:Flask):
    app.register_blueprint(bp_band)

ieq_cifras/BluePrints/band/routes.py
from . import bp_band
from .forms import NewBandForm

# from ieq_cifras.Extensions.database import database
from ieq_cifras.models import User, Band, BandMember
from ieq_cifras.Extensions.database import database

from flask import render_template, request, redirect, url_for, abort

from flask_login import login_required, current_user

'''This is the view of the band'''
@bp_band.route('/<id_band>')
def home(id_band):
    band = Band.query.get(id_band)
    if not band:
        return abort(404)
    if current_user not in band.users:
        return abort(401)
    return render_template('bandHome.html', band=band)
    # return f'{band.name}| {band.users}'


@bp_band.route('/my_bands')
@login_required
def my_bands():
    list_bandMembers = BandMember.query.filter_by(id_user = current_user.id, is_del=False).all()
    list_bandIDs = [bandMember.id for bandMember in list_bandMembers]
    list_bands = database.session.query(Band).filter(Band.id.in_(list_bandIDs)).all()
    list_bands = current_user.bands
    return render_template('my_bands.html', list_bands= list_bands)

@bp_band.route('/new', methods=['GET', 'POST'])
@login_required
def new(): 
    form_newBand  = NewBandForm()
    if request.method == 'GET': # when accessing the page
        return render_template('new.html', title='New Band', form=form_newBand)
    elif request.method == 'POST':
        if form_newBand.validate_on_submit():
            new_band = Band(name=form_newBand.name.data, id_manager=current_user.id)
            database.session.add(new_band)
            database.session.commit()
            new_bandMember = BandMember(id_user = current_user.id, id_band=new_band.id)
            database.session.add(new_bandMember)
            database.session.commit()
            return redirect(url_for('band.my_bands'))
        else:
            return render_template('new.html', title='New Band', form=form_newBand)

@bp_band.route('/<id_band>/invite')
@login_required
def invite(id_band):
    band = Band.query.get(id_band)
    if current_user.id != band.id_manager:
        return abort(401)
    
    
    return render_template('invite.html', band=band)

@bp_band.route('/<id_band>/enter/<access_key>', methods=[ 'GET', 'POST'])
@login_required
def enter(id_band, access_key):
    band = Band.query.get(id_band)
    if band.access_key != access_key: # verify if key is correct
        return 'chave inválida'
    elif current_user in band.users: # verify if user is already in band
        return 'você ja está nessa banda'
    
    if request.method == 'GET':
        return render_template('enter.html', band=band)
    elif request.method == 'POST':
        bandMember = BandMember(id_user = current_user.id, id_band = band.id)
        database.session.add(bandMember)
        database.session.commit()
        return redirect(url_for('band.home', id_band = id_band))

ieq_cifras/BluePrints/band/templates/bandHome.html
{% extends 'base.html'%}

{% block content %}

<div>
    <h1>Aqui é a página home de uma banda</h1>
</div>

<div>
    <a>
        <button>
            Nova Cifra
        </button>
    </a>
    <a>
        <button>
            Nossas Cifras
        </button>
    </a>
    {% if current_user.id == band.id_manager %}
        <a>
            <button>
                Editar banda
            </button>
        </a>
        <a href="{{url_for('band.invite', id_band = band.id)}}">
            <button>
                Link convite
            </button>
        </a>
    {% endif %}
</div>

<div>
    <h2>
        Membros
    </h2>
    <ul>
        {% for user in band.users %}
            <li>
                {{ user.username }}
            </li>
        {% endfor %}
    </ul>
</div>

{% if current_user.id != band.id_manager %}
    <div>
        <a>
            <button>
                Sair
            </button>
        </a>
    </div>    
{% endif %}

{% endblock content %}

ieq_cifras/BluePrints/band/templates/enter.html
{% extends 'base.html'%}

{% block content %}

<div>
    <h1>Aqui é a página de enter banda</h1>
</div>

<div>
    <h2>
        Entrar na banda {{band.name}}
    </h2>

    <form action="" method="POST">
        <input type="submit" value="Enter">
    </form>

</div>

{% endblock content %}

ieq_cifras/BluePrints/band/templates/invite.html
{% extends 'base.html'%}

{% block content %}

<div>
    <h1>Aqui é a página de invite</h1>
</div>

<div>
    <h2>
        Link convite
    </h2>
    <input type="text" value="{{url_for('band.enter', id_band=band.id, access_key=band.access_key, _external=True)}}" id="myInput" readonly>
    <button onclick="myFunction()">Copy text</button>

    <button>
        Generate new link
    </button>

</div>

<script>
function myFunction() {
  var copyText = document.getElementById("myInput");
  copyText.select();
  document.execCommand("Copy");
  alert("Copied to clipboard");
}    
</script>

{% endblock content %}

ieq_cifras/BluePrints/band/templates/my_bands.html
{% extends 'base.html'%}

{% block content %}

<div>
    <h1>Aqui é a página de my bands</h1>
</div>

<div>
    <h2>
        Minhas bandas
    </h2>
    <ul>
        {% for band in list_bands %}
            <li>
                <a href="{{url_for('band.home', id_band=band.id)}}">
                    {{ band.name }}
                </a>
            </li>
        {%endfor %}
    </ul>
</div>

<div>
    
    <a href="{{url_for('band.new')}}"">
        <button>
            Criar banda
        </button>
    </a>
    
</div>

{% endblock content %}

ieq_cifras/BluePrints/band/templates/new.html
{% extends 'base.html'%}

{% block content %}

<div>
    <h1>Aqui é a página de new band</h1>
</div>


<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <legend class="border-bottom mb4">Login</legend>
        <fieldset class="form-group">
            <div class=""form-group>
                {{ form.name.label(class='form-control-label') }}
                {% if form.name.errors %}
                    {{ form.name(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class='form-control form-control-lg') }}
                {% endif %}
            </div>
            <div class=""form-group>
                {{ form.submit(class='btn tbn-outline-info') }}
            </div>
        </fieldset>
    </form>
</div>

<div>
    
</div>

{% endblock content %}